//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Bills = new HashSet<Bill>();
            this.CustomerFeedbacks = new HashSet<CustomerFeedback>();
        }
    
        public string AccountID { get; set; }
        public string OrderID { get; set; }
        public int ServiceID { get; set; }
        public int PaymentPlanDetailID { get; set; }
        public int CustomerID { get; set; }
        public int ConnectQuantity { get; set; }
        public string Status { get; set; }
        public string ContactNumber { get; set; }
        public System.DateTime ConnectedAt { get; set; }
        public System.DateTime DueDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PaymentPlanDetail PaymentPlanDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerFeedback> CustomerFeedbacks { get; set; }
    }
}
