//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Charges = new HashSet<Charge>();
        }
    
        public int BillID { get; set; }

        [Required(ErrorMessage = "Account ID is require")]
        public string AccountID { get; set; }

        public int EmployeeID { get; set; }

        [DisplayName("Initial Due Amount")]
        [Required(ErrorMessage = "Initial Due Amount is require")]
        public double InitialDueAmount { get; set; }

        [DisplayName("Amount Paid")]
        [Required(ErrorMessage = "Amount Paid is require")]
        public double AmountPaid { get; set; }

        [Required(ErrorMessage = "Discount is require")]
        public double Discount { get; set; }

        [DisplayName("VAT Cost")]
        [Required(ErrorMessage = "Vat Cost is require")]
        public double VatCost { get; set; }

        [DisplayName("Paid Content")]
        [Required(ErrorMessage = "Paid Content is require")]
        public string PaidContent { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }

        // Other properties
        [DisplayName("Is Paid")]
        public bool Paid { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Charge> Charges { get; set; }
    }
}
