//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Billing()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int BillingID { get; set; }
        public int PackageID { get; set; }
        public string CustomerID { get; set; }
        public string Status { get; set; }
        public int TotalPrice { get; set; }
        public Nullable<int> MonthCount { get; set; }
        public string Description { get; set; }
        public string CreatedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Package Package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
