//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillID { get; set; }
        public int ConnectionID { get; set; }
        public int AmountPaid { get; set; }
        public string PaidContent { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Connection Connection { get; set; }
    }
}
