//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallCharge
    {
        public int CallChargeID { get; set; }
        public int PaymentPlanDetailID { get; set; }
        public int CallChargeTypeID { get; set; }
        public int CostPerMinute { get; set; }
    
        public virtual CallChargeType CallChargeType { get; set; }
        public virtual PaymentPlanDetail PaymentPlanDetail { get; set; }
    }
}
