//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Charge
    {
        public int ChargeID { get; set; }

        [Required(ErrorMessage = "BillID is require")]
        public int BillID { get; set; }

        [DisplayName("Charge Name")]
        [Required(ErrorMessage = "Charge name is require")]
        public string ChargeName { get; set; }

        [DisplayName("Charge Value (cents)")]
        [Required(ErrorMessage = "Charge value is require")]
        public int Value { get; set; }

        [Required(ErrorMessage = "Description is require")]
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
