//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charge
    {
        public int ChargeID { get; set; }
        public string ChargeName { get; set; }
        public int Value { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
