//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connect
    {
        public int ConnectID { get; set; }
        public string CustomerID { get; set; }
        public int PackageID { get; set; }
        public string Status { get; set; }
        public int DueAmount { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Package Package { get; set; }
    }
}
