//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFeedback
    {
        public int CustomerFeedbackID { get; set; }
        public string AccountID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Content { get; set; }
        public string ReplyContent { get; set; }
        public System.DateTime FeedbackAt { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
