//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.WarehouseEquipments = new HashSet<WarehouseEquipment>();
        }
    
        public int EquipmentID { get; set; }
        [Required(ErrorMessage = "Supplier id can not empty")]
        public int SupplierID { get; set; }
        [Required(ErrorMessage = "Equipment name can not empty")]
        public string EquipmentName { get; set; }
        [Required(ErrorMessage = "Description can not empty")]
        public string Description { get; set; }
        public string Image { get; set; }
        public HttpPostedFileBase imageFile { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseEquipment> WarehouseEquipments { get; set; }
    }
}
