//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderID { get; set; }
        public string CustomerID { get; set; }
        public int PackageID { get; set; }
        public string Status { get; set; }
        public int Deposit { get; set; }
        public int Price { get; set; }
        public double Discount { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int MonthCount { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Package Package { get; set; }
    }
}
