//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int BillingID { get; set; }
        public int EmployeeID { get; set; }
        public int AmountPaid { get; set; }
        public string PaymentContent { get; set; }
        public System.DateTime PaidDate { get; set; }
    
        public virtual Billing Billing { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
