//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentPlanDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentPlanDetail()
        {
            this.ConnectionPaymentPlans = new HashSet<ConnectionPaymentPlan>();
        }
    
        public int PaymentPlanDetailID { get; set; }
        public int PaymentPlanID { get; set; }
        public string Content { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectionPaymentPlan> ConnectionPaymentPlans { get; set; }
        public virtual PaymentPlan PaymentPlan { get; set; }
    }
}
