//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailShowRoomEmployee
    {
        public int ID { get; set; }
        public int RetailShowRoomID { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual RetailShowRoom RetailShowRoom { get; set; }
    }
}
