//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.Web;

    public partial class RetailShowRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RetailShowRoom()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int RetailShowRoomID { get; set; }

        
        [Required(ErrorMessage = "Employee name can not empty")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Phone can not empty")]
        [RegularExpression("[0-9]{10}", ErrorMessage = "Phone only accept 10 number (0-9)")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Address can not empty")]
        public string Address { get; set; }
        public string Image { get; set; }
        public HttpPostedFileBase imageFile { get; set; }

        [Required(ErrorMessage = "Quantity can not empty")]
        [RegularExpression("[1-9]", ErrorMessage = "The number of employees cannot be negative")]
        public int EmployeeQuantity { get; set; }

        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
