//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehouse()
        {
            this.WarehouseEquipments = new HashSet<WarehouseEquipment>();
        }
    
        public int WarehouseID { get; set; }
        [Required(ErrorMessage = "Name can not empty")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Address can not empty")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Contact number can not empty")]
        [RegularExpression("[0-9]{10}", ErrorMessage = "Contact number only accept 10 number (0-9)")]
        public string ContactNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseEquipment> WarehouseEquipments { get; set; }
    }
}
